
logging:
  config: classpath:log/logback-test.xml


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


server:
  port: 8080


#spring:
#  datasource:
#    url: jdbc:mysql://192.168.0.132:3306/credit-manager?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
